import { Hamburger, House, Utensils } from "lucide-react";

export const NAV_LINKS = [
  {
    to: "/",
    label: "Home",
    icon: <House className="size-5" />,
  },
  {
    to: "/meals",
    label: "Meals",
    icon: <Hamburger className="size-5" />,
  },
  {
    to: "/upcoming-meals",
    label: "Upcoming Meals",
    icon: <Utensils className="size-5" />,
  },
];

export const MEALS = [
  {
    title: "Grilled Chicken Rice Bowl",
    category: "Lunch",
    image: "https://i.ibb.co/hvhF058/meal-1.jpg",
    ingredients: ["Chicken Breast", "Rice", "Broccoli", "Carrots", "Soy Sauce"],
    description:
      "A protein-packed rice bowl with grilled chicken and steamed vegetables.",
    price: 6,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Vegetable Pasta",
    category: "Dinner",
    image: "https://i.ibb.co/n8nwXCYF/meal-2.jpg",
    ingredients: ["Pasta", "Tomato", "Bell Peppers", "Onion", "Basil"],
    description: "A healthy and delicious vegetable pasta perfect for dinner.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Cheese Omelette",
    category: "Breakfast",
    image: "https://i.ibb.co/F4qrpppQ/meal-3.jpg",
    ingredients: ["Eggs", "Cheese", "Onion", "Bell Peppers"],
    description:
      "Fluffy cheese omelette served hot for a protein-rich breakfast.",
    price: 3,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Paneer Butter Masala",
    category: "Lunch",
    image: "https://i.ibb.co/fgTxLq9/meal-4.jpg",
    ingredients: ["Paneer", "Butter", "Tomato", "Cream", "Spices"],
    description: "Rich and creamy paneer butter masala served with warm rotis.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Fruit Salad",
    category: "Breakfast",
    image: "https://i.ibb.co/rf1QbRQ0/meal-5.jpg",
    ingredients: ["Apple", "Banana", "Orange", "Grapes", "Honey"],
    description:
      "Refreshing fruit salad with seasonal fruits and a drizzle of honey.",
    price: 2,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Chicken Curry",
    category: "Dinner",
    image: "https://i.ibb.co/DgSTB2P0/meal-6.jpg",
    ingredients: ["Chicken", "Onion", "Tomato", "Spices", "Coriander"],
    description: "Spicy chicken curry served with steamed rice or roti.",
    price: 6,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Veg Sandwich",
    category: "Lunch",
    image: "https://i.ibb.co/wNR2jzDN/meal-7.jpg",
    ingredients: ["Bread", "Cucumber", "Tomato", "Cheese", "Lettuce"],
    description: "A quick and healthy vegetable sandwich with cheese.",
    price: 3,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Dal Tadka",
    category: "Lunch",
    image: "https://i.ibb.co/tpdHJ11q/meal-8.jpg",
    ingredients: ["Lentils", "Onion", "Tomato", "Garlic", "Spices"],
    description: "Classic Indian dal tadka served with steamed rice.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Veg Fried Rice",
    category: "Lunch",
    image: "https://i.ibb.co/8Dy1gyyX/meal-9.jpg",
    ingredients: ["Rice", "Carrots", "Peas", "Capsicum", "Soy Sauce"],
    description: "Tasty vegetable fried rice cooked with soy sauce and spices.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Pancakes with Syrup",
    category: "Breakfast",
    image: "https://i.ibb.co/WpgC9Ccz/meal-10.jpg",
    ingredients: ["Flour", "Milk", "Eggs", "Maple Syrup", "Butter"],
    description: "Fluffy pancakes served with butter and maple syrup.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Chole Bhature",
    category: "Lunch",
    image: "https://i.ibb.co/svFVVF8Q/meal-11.jpg",
    ingredients: ["Chickpeas", "Flour", "Onion", "Tomato", "Spices"],
    description: "Spicy chickpea curry served with fluffy fried bread.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Fruit Smoothie",
    category: "Breakfast",
    image: "https://i.ibb.co/YBYDZKqZ/meal-12.jpg",
    ingredients: ["Banana", "Berries", "Milk", "Honey"],
    description: "Refreshing fruit smoothie blended with milk and honey.",
    price: 3,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Masala Dosa",
    category: "Breakfast",
    image: "https://i.ibb.co/CK9C9k3F/meal-13.jpg",
    ingredients: ["Rice", "Potato", "Onion", "Spices"],
    description: "Crispy masala dosa filled with spiced potato filling.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Veg Biryani",
    category: "Dinner",
    image: "https://i.ibb.co/PZjNyyzP/meal-14.jpg",
    ingredients: ["Rice", "Vegetables", "Spices", "Onion"],
    description: "Flavorful vegetable biryani cooked with aromatic spices.",
    price: 6,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Chapati with Sabzi",
    category: "Lunch",
    image: "https://i.ibb.co/JwnN8MgB/meal-15.jpg",
    ingredients: ["Wheat Flour", "Mixed Vegetables", "Spices"],
    description: "Soft chapatis served with seasonal vegetable curry.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Mango Lassi",
    category: "Snacks",
    image: "https://i.ibb.co/qMctTS8j/meal-16.jpg",
    ingredients: ["Mango", "Yogurt", "Sugar", "Cardamom"],
    description: "Sweet and refreshing mango lassi with cardamom flavor.",
    price: 2,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Egg Fried Rice",
    category: "Lunch",
    image: "https://i.ibb.co/v4BcP0Xt/meal-17.jpg",
    ingredients: ["Rice", "Egg", "Vegetables", "Soy Sauce"],
    description: "Tasty egg fried rice with vegetables and soy sauce.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Aloo Paratha",
    category: "Breakfast",
    image: "https://i.ibb.co/1GCjTRGL/meal-18.jpg",
    ingredients: ["Wheat Flour", "Potato", "Spices", "Butter"],
    description: "Stuffed potato paratha served with butter for breakfast.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Chicken Wrap",
    category: "Snacks",
    image: "https://i.ibb.co/nNN5MkHN/meal-19.jpg",
    ingredients: ["Tortilla", "Chicken", "Lettuce", "Tomato", "Sauce"],
    description: "Grilled chicken wrap with fresh vegetables and sauce.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Tomato Soup",
    category: "Dinner",
    image: "https://i.ibb.co/dstLFT2W/meal-20.jpg",
    ingredients: ["Tomato", "Onion", "Garlic", "Spices"],
    description: "Warm and comforting tomato soup served with croutons.",
    price: 3,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Banana Pancakes",
    category: "Breakfast",
    image: "https://i.ibb.co/RkJHWPWx/meal-21.jpg",
    ingredients: ["Banana", "Flour", "Milk", "Eggs"],
    description: "Sweet and fluffy banana pancakes for a delightful breakfast.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Fish Curry",
    category: "Dinner",
    image: "https://i.ibb.co/Nnk5Hv3Q/meal-22.jpg",
    ingredients: ["Fish", "Onion", "Tomato", "Spices"],
    description: "Spicy fish curry served with steamed rice.",
    price: 6,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Club Sandwich",
    category: "Snacks",
    image: "https://i.ibb.co/LDBcNVLR/meal-23.jpg",
    ingredients: ["Bread", "Chicken", "Lettuce", "Tomato", "Mayonnaise"],
    description: "Classic club sandwich layered with chicken and vegetables.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Veg Pulao",
    category: "Lunch",
    image: "https://i.ibb.co/JW8srjCq/meal-24.jpg",
    ingredients: ["Rice", "Mixed Vegetables", "Spices"],
    description: "Aromatic vegetable pulao cooked with spices and herbs.",
    price: 5,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Veg Burger",
    category: "Snacks",
    image: "https://i.ibb.co/v4hLcVqv/meal-25.jpg",
    ingredients: ["Burger Bun", "Veg Patty", "Lettuce", "Tomato", "Sauce"],
    description: "Delicious veg burger served with fresh vegetables and sauce.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Chicken Biryani",
    category: "Dinner",
    image: "https://i.ibb.co/HTMnZMqF/meal-26.jpg",
    ingredients: ["Rice", "Chicken", "Spices", "Onion"],
    description: "Fragrant chicken biryani cooked with aromatic spices.",
    price: 7,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Idli with Sambar",
    category: "Breakfast",
    image: "https://i.ibb.co/TxbzgWNR/meal-27.webp",
    ingredients: ["Rice", "Lentils", "Spices", "Vegetables"],
    description: "Soft idlis served with flavorful sambar for breakfast.",
    price: 3,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Veg Momos",
    category: "Snacks",
    image: "https://i.ibb.co/GvtNr55G/meal-28.jpg",
    ingredients: ["Flour", "Vegetables", "Spices"],
    description: "Steamed vegetable momos served with spicy chutney.",
    price: 4,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Peanut Butter Toast",
    category: "Breakfast",
    image: "https://i.ibb.co/F4nX5RvB/meal-29.jpg",
    ingredients: ["Bread", "Peanut Butter"],
    description: "Simple peanut butter toast for a quick breakfast.",
    price: 2,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
  {
    title: "Samosa",
    category: "Snacks",
    image: "https://i.ibb.co/JW8Tw90J/meal-30.jpg",
    ingredients: ["Flour", "Potato", "Peas", "Spices"],
    description: "Crispy samosa stuffed with spiced potato and peas.",
    price: 2,
    postTime: new Date(),
    rating: 0,
    likes: 0,
    reviews_count: 0,
    distributor_name: "John Doe",
    distributor_email: "test@gmail.com",
  },
];
